language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo test --all-features
  - cargo test --no-default-features
  - cargo test --no-default-features --features events
  - cargo test --no-default-features --features par-iter
  - cargo test --no-default-features --features ffi
  - cargo test --release --all-features
  - cargo test --release --no-default-features
  - cargo test --release --no-default-features --features events
  - cargo test --release --no-default-features --features par-iter
  - cargo test --release --no-default-features --features ffi
