[package]
name = "legion"
version = "0.1.1"
description = "High performance entity component system (ECS) library"
authors = ["Thomas Gillen <thomas.gillen@googlemail.com>"]
repository = "https://github.com/TomGillen/legion"
keywords = ["ecs", "game"]
categories = ["game-engines", "data-structures"]
readme = "readme.md"
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "TomGillen/legion", branch = "master" }

[features]
default = ["par-iter", "events"]
par-iter = ["rayon", "crossbeam"]
ffi = []
events = []
serde-1 = ["serde"]

[dependencies]
parking_lot = "0.9"
downcast-rs = "1.0"
itertools = "0.8"
rayon = { version = "1.2", optional = true }
crossbeam = { version = "0.7", optional = true }
derivative = "1"
smallvec = "0.6"
bit-set = "0.5"
paste = "0.1"
log = "0.4"
shrinkwraprs = "0.2"
mopa = "0.2"
serde = { version = "1", optional = true }

[dev-dependencies]
env_logger = "0.7"
criterion = "0.3"
cgmath = "0.17"
legion = { features = ["serde-1"], path = "." }
serde_json = "1.0"
type-uuid = "0.1"
erased-serde = "0.3"
serde = { version = "1", features = ["derive"]}
uuid = { version = "0.8", features = ["v4"] }

[[bench]]
name = "benchmarks"
harness = false

[[bench]]
name = "parallel_query"
harness = false

[[bench]]
name = "transform"
harness = false
